spring:
  application:
    name: appraisal-api-gateway
  config:
    import: optional:configserver:http://localhost:8888

logging:
  level:
    reactor:
      netty: TRACE
    org:
      springframework:
        cloud:
          gateway: TRACE