apiVersion: apps/v1
kind: Deployment
metadata:
  name: appraisal-cloud-gateway-app
spec:
  selector:
    matchLabels:
      app: appraisal-cloud-gateway-app
  replicas: 1
  template:
    metadata:
      labels:
        app: appraisal-cloud-gateway-app
    spec:
      containers:
        - name: appraisal-cloud-gateway-app
          image: lolalambe/appraisal-api-gateway:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 9191
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
            - name: CONFIG_URL
              value: http://appraisal-config-server-app-0.appraisal-config-server-app.default.svc.cluster.local:8888