apiVersion: v1
kind: Service
metadata:
  name: appraisal-cloud-gateway-service
spec:
  type: LoadBalancer
  selector:
    app: appraisal-cloud-gateway-app
  ports:
    - targetPort: 9191
      port: 80
      protocol: TCP